[package]
name = "ecu"
version = "0.1.0"
authors = ["David Allen <19dallen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.11"

[dependencies.hal]
path = "../hal"
